# Generated by Django 4.2.23 on 2025-07-04 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('national_id', models.CharField(max_length=14)),
                ('is_valid', models.BooleanField()),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('response_status', models.IntegerField()),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_framework_api_key.apikey')),
            ],
        ),
    ]
